name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v22.14.0
      uses: actions/setup-node@v3
      with:
        node-version: '22.14.0'
    - name: Install dependencies
      run: npm i
    - name: Print image tag
      run: echo "${{ secrets.DOCKER_USERNAME }}/qp-assessment:latest"
    - name: Build the Docker image
      run: |
        IMAGE=${{ secrets.DOCKER_USERNAME }}/qp-assessment:latest
        echo "Building image: $IMAGE"
        docker build --file Dockerfile . -t $IMAGE
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/qp-assessment:latest
